shinano-common: tfa: Add missing  header
avoid warning as:

device/sony/shinano/libaudioamp/tfa9890.c: In function 'tfa9890_prepare_for_ioctl':
device/sony/shinano/libaudioamp/tfa9890.c:53:2: warning: implicit declaration of function 'free' [-Wimplicit-function-declaration]
  free(tfa9890_param_data.data);
  ^
device/sony/shinano/libaudioamp/tfa9890.c:53:2: warning: incompatible implicit declaration of built-in function 'free'

https://github.com/sonyxperiadev/device-sony-shinano/commit/2aed9e2f4a51bdca13f4403457d6f4483e09b8e5

Change-Id: I6dda71087618b6f9925ae8b3203f675f298d81f6